export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: 'Dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: 'Workbench',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 2,
    pid: 1,
  },
  {
    name: 'list',
    path: '/list',
    title: 'List page',
    requiresAuth: true,
    icon: 'icon-park-outline:list-two',
    menuType: 'dir',
    componentPath: null,
    id: 10,
    pid: null,
  },
  {
    name: 'roomList',
    path: '/list/roomList',
    title: 'Commonly used list',
    requiresAuth: true,
    icon: 'icon-park-outline:list-view', componentPath: '/letan/phong/index.vue',
    id: 11,
    pid: 10,
  },
  {
    name: 'roomType',
    path: '/list/roomType',
    title: 'Loại phòng',
    requiresAuth: true,
    icon: 'icon-park-outline:list-view', componentPath: '/letan/loaiphong/index.vue',
    id: 12,
    pid: 10,
  },
   {
    name: 'tagType',
    path: '/list/tagType',
    title: 'Tag',
    requiresAuth: true,
    icon: 'icon-park-outline:list-view', componentPath: '/letan/tag/index.vue',
    id: 13,
    pid: 10,
  },
  {
    name: 'datPhong',
    path: '/letan/datphong',
    title: 'Đăt phòng',
    requiresAuth: true,
    icon: 'mdi:bed-outline',
    componentPath: '/letan/datphong/index.vue',
    id: 20,
    pid: null,
  },
  {
    name: 'userCenter',
    path: '/userCenter',
    title: 'Personal Center',
    requiresAuth: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/demo/userCenter/index.vue',
    id: 39,
    pid: null,
  },

]
